locations:
  door_1:
    w: 0.026
    x: -1.364
    y: 2.247
    z: 1.0
  door_2:
    w: 0.706
    x: 1.273
    y: -3.954
    z: 0.708
  hall_corner:
    w: 0.561
    x: -2.653
    y: -2.639
    z: -0.828
  room_center:
    w: 0.993
    x: 3.232
    y: 0.029
    z: 0.122
